#############################################################################
# Makefile for building: QTDMGProj.app/Contents/MacOS/QTDMGProj
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  ../QTDMGProj/QTDMGProj.pro
# Template: app
# Command: /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake -o Makefile ../QTDMGProj/QTDMGProj.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../QTDMGProj -I. -I../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtPrintSupport.framework/Headers -I../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers -I../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang -F/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib
QMAKE         = /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QTDMGProj1.0.0
DISTDIR = /Users/arqam/Desktop/Junk/build-QTDMGProj-Desktop_Qt_5_10_0_clang_64bit-Debug/.tmp/QTDMGProj1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../QTDMGProj/main.cpp \
		../QTDMGProj/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qdevice.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/device_config.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/unix.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/mac.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/macx.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qconfig.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		../QTDMGProj/.qmake.stash \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_post.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qml_debug.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resources.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/moc.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/uic.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/yacc.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/lex.prf \
		../QTDMGProj/QTDMGProj.pro ../QTDMGProj/mainwindow.h ../QTDMGProj/main.cpp \
		../QTDMGProj/mainwindow.cpp
QMAKE_TARGET  = QTDMGProj
DESTDIR       = 
TARGET        = QTDMGProj.app/Contents/MacOS/QTDMGProj

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d QTDMGProj.app/Contents/MacOS/ || mkdir -p QTDMGProj.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../QTDMGProj/QTDMGProj.pro ../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf ../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qdevice.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/device_config.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/unix.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/mac.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/macx.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qconfig.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_post.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qml_debug.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resources.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/moc.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/uic.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/yacc.prf \
		../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/lex.prf \
		../QTDMGProj/QTDMGProj.pro \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile ../QTDMGProj/QTDMGProj.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_pre.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qdevice.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/device_config.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/unix.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/mac.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/macx.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/sanitize.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/common/clang-mac.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/qconfig.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_functions.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt_config.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/sdk.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/toolchain.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_pre.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resolve_config.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/default_post.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/default_post.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qml_debug.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/warn_on.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qt.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/resources.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/moc.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/opengl.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/uic.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/unix/thread.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/qmake_use.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/file_copies.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/rez.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/testcase_targets.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/exceptions.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/yacc.prf:
../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/lex.prf:
../QTDMGProj/QTDMGProj.pro:
../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl:
../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../QTDMGProj/QTDMGProj.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

QTDMGProj.app/Contents/PkgInfo: 
	@test -d QTDMGProj.app/Contents || mkdir -p QTDMGProj.app/Contents
	@$(DEL_FILE) QTDMGProj.app/Contents/PkgInfo
	@echo "APPL????" > QTDMGProj.app/Contents/PkgInfo
QTDMGProj.app/Contents/Resources/empty.lproj: 
	@test -d QTDMGProj.app/Contents/Resources || mkdir -p QTDMGProj.app/Contents/Resources
	@touch QTDMGProj.app/Contents/Resources/empty.lproj
	
QTDMGProj.app/Contents/Info.plist: 
	@test -d QTDMGProj.app/Contents || mkdir -p QTDMGProj.app/Contents
	@$(DEL_FILE) QTDMGProj.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Mobigraph.QTDMGProj,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,QTDMGProj,g" -e "s,@LIBRARY@,QTDMGProj,g" -e "s,@TYPEINFO@,????,g" ../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang/Info.plist.app >QTDMGProj.app/Contents/Info.plist

all: Makefile \
		QTDMGProj.app/Contents/PkgInfo \
		QTDMGProj.app/Contents/Resources/empty.lproj \
		QTDMGProj.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../QTDMGProj/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../QTDMGProj/main.cpp ../QTDMGProj/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../QTDMGProj/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r QTDMGProj.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../ImageToCartoon/QT/5.10.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../QTDMGProj/mainwindow.h \
		moc_predefs.h \
		../../ImageToCartoon/QT/5.10.0/clang_64/bin/moc
	/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/mkspecs/macx-clang -I/Users/arqam/Desktop/Junk/QTDMGProj -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtGui.framework/Headers -I/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/lib ../QTDMGProj/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../QTDMGProj/mainwindow.ui \
		../../ImageToCartoon/QT/5.10.0/clang_64/bin/uic
	/Users/arqam/Desktop/ImageToCartoon/QT/5.10.0/clang_64/bin/uic ../QTDMGProj/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../QTDMGProj/main.cpp ../QTDMGProj/mainwindow.h \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../QTDMGProj/main.cpp

mainwindow.o: ../QTDMGProj/mainwindow.cpp ../QTDMGProj/mainwindow.h \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../ImageToCartoon/QT/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../QTDMGProj/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

